# Generated by Django 3.1.2 on 2020-11-17 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatePage',
            fields=[
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, unique=True)),
                ('weight', models.FloatField(default=1)),
                ('height', models.FloatField(default=1)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='Male', max_length=20)),
                ('disease', models.CharField(choices=[('no disease', ' no disease'), ('disease', 'disease'), ('disease', 'disease'), ('disease', 'disease')], default='no disease', max_length=20)),
                ('region', models.CharField(default='No place', max_length=30)),
            ],
        ),
    ]
