# Generated by Django 3.1.2 on 2020-11-01 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_model',
            old_name='date_birth',
            new_name='date',
        ),
    ]
